language: node_js
sudo: true
node_js:
  - "5.0"
install:
  - npm install -g babel-cli
  - npm install
addons:
  code_climate:
    repo_token: f932c43d4ad44f04db1c05dd1bd2de3616affcec12bb9ce3171f5b01d5f17741
